PIPELINE_TYPE: 'Voice2Pose'

VOICE2POSE:
  GENERATOR:
    NAME: 'SequenceGeneratorCNN'
    LOSS_REG: 'L1Loss'
    CLIP_CODE:
      DIMENSION: 32
      EXTERNAL_CODE: False

DATASET:
  NAME: 'speech2gesture'
  ROOT_DIR: 'datasets/speech2gesture'
